services:
  - type: web
    name: hirelens-ai-backend
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: API_PREFIX
        value: /api/v1
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: qwen2.5:3b
      - key: CLIENT_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: LOG_LEVEL
        value: info
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false